name: 'buildTestAndPublish'
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:   
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
          
      - name: Build bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command
          
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test # will run `yarn test` command
      
      - name: End-To-End testing
        uses: borales/actions-yarn@v4
        with:
          cmd: test:e2e

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/reports/**/*.xml'
        
